package com.ulfric.buycraft.sco.model;

public enum StandardCheckoutError {

	INTERNAL_ERROR,
	MISSING_BUYCRAFT_TOKEN,
	MISSING_SCO_TOKEN,
	MISSING_WEBSTORE_ID,
	MISSING_CART_OR_PRICE,
	CART_AND_PRICE_PRESENT,
	MISSING_PURCHASER,
	INVALID_WEBSTORE,
	INCORRECT_SCO_TOKEN,
	INCORRECT_BUYCRAFT_TOKEN,
	BUYCRAFT_ERROR,
	BUYCRAFT_ERROR_ADDING,
	PRICE_TOO_HIGH,
	INVALID_PRICE;

}
