package com.ulfric.buycraft.sco.model;

public enum StandardCheckoutError {

	INTERNAL_ERROR,
	MISSING_BUYCRAFT_TOKEN,
	MISSING_SCO_TOKEN,
	MISSING_WEBSTORE_ID,
	MISSING_CART,
	MISSING_PURCHASER,
	INVALID_WEBSTORE,
	INCORRECT_SCO_TOKEN,
	INCORRECT_BUYCRAFT_TOKEN,
	PAYMENT_FAILED;

}
